version: 2.1
orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - python/load-cache
      - run:
          name: install latest influxdb
          command: |
            wget -qO- https://repos.influxdata.com/influxdb.key | sudo apt-key add -
            source /etc/lsb-release
            echo "deb https://repos.influxdata.com/${DISTRIB_ID,,} ${DISTRIB_CODENAME} stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
            sudo apt-get update
            sudo apt-get install -y influxdb
            sudo /etc/init.d/influxdb start
      - run:
          name: install dev/test requirements
          command: |
            sudo pip install -r requirements-test.txt
      - python/save-cache
      - run:
          name: lint checks
          command: |
            for f in `find ./ -name '*py' | grep -v test | grep -v venv`; do pyflakes $f; done
      - run:
          name: run tests
          command: |
            coverage run --source=candles -m pytest

      - store_test_results:
          path: .coverage
      - store_artifacts:
          path: .coverage
          destination: .coverage
      - run:
          name: coveralls upload
          command: |
            COVERALLS_REPO_TOKEN=${COVERALLS_TOKEN} coveralls

workflows:
  main:
    jobs:
      - build-and-test
